### ISSUE TITLE
Nested structures do not work. (array of array of classes)

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/assemblyscript#18]
fiddle that reproes https://studio.nearprotocol.com/?f=opapxvcfg

fails on assert(name == null); in the following code
```export class __near_JSONHandler_Array_Array_GameCellData extends ThrowingJSONHandler {
      buffer: Uint8Array;
      decoder: JSONDecoder<__near_JSONHandler_Array_Array_GameCellData>;
      handledRoot: boolean = false;
      value: Array<Array<wrapped_GameCellData>> = new Array<Array<wrapped_GameCellData>>();
pushObject(name: string): bool {
        this.value.push(<Array<GameCellData>>__near_decode_Array_GameCellData(this.buffer, this.decoder.state));
        return false;
      }
      pushArray(name: string): bool {
        assert(name == null);
        if (!this.handledRoot) {
          this.handledRoot = true;
          return true;
        }
        this.value.push(<Array<GameCellData>>__near_decode_Array_GameCellData(this.buffer, this.decoder.state));
        return false;
      }```

**Comment by janedegtiareva** [comment]
This is the smallest fiddle that I could get to repro the bug https://studio.nearprotocol.com/?f=rw4kghq7a

**Comment by vgrichina** [comment]
Updated for latest NEARLib https://studio.nearprotocol.com/?f=i98us2ahd

**Comment by vgrichina** [comment]
This got somewhat blocked by https://github.com/AssemblyScript/assemblyscript/issues/473 (
https://github.com/AssemblyScript/assemblyscript/issues/429 to be more specific).

I'll try to restructure tests to get around this though.

**Comment by vgrichina** [comment]
Actual bug was with `null` handling delaying error significantly:
https://github.com/AssemblyScript/assemblyscript/issues/507

**Comment by vgrichina** [comment]
Closing, tests are here https://github.com/nearprotocol/assemblyscript/pull/22
